version: "2.4"

services:
  portal_api:
    entrypoint: /bin/true
  registration_api:
    entrypoint: /bin/true
  analytics_feed:
    entrypoint: /bin/true
  nginx:
    entrypoint: /bin/true
  notification-service:
    entrypoint: /bin/true
  digilocker_support_api:
    entrypoint: /bin/true
  flagr:
    entrypoint: /bin/true
  clickhouse-server:
    entrypoint: /bin/true
  keycloak:
    environment:
      - KEYCLOAK_IMPORT=/config/e2e-divoc-realm.json
    volumes:
      - ./keycloak:/config
  certificate_processor:
      environment:
        ADMIN_API_CLIENT_SECRET: a1832880-059a-40d0-86b1-e318ced82613
  e2e_test:
    build:
      context: ./e2e
    container_name: e2e_test
    depends_on: 
      vaccination_api:
        condition: service_started
      keycloak:
        condition: service_healthy
      registry:
        condition: service_started
