registry:
  url: http://localhost:8081
  addoperationid: add
  searchoperationid: search
  readoperationid: read
keycloak:
  url: https://divoc.togosafe.gouv.tg/keycloak/auth
  realm: divoc
  pubkey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoV9jMzgQTHgDKKK2cqXskOezYpEBrT7mhy6abSUJIMrq8mLQG4DVyhotihMmLqdqei2FjsTaiBWwyBEBJzrY3WuxTKkuUr9dKRXpoCDtR+QLmN6a6vjS7Dl/rQ3JLRTZwnCPJP1l0ZeUCenajPczceUm27SNUnsJSXgKC82bIwa5pz3HS/M4Eqjy26WIspJhI5BbvuEcI1CHtr8Eeb+iU2d8WCcH8Z3UP9XBtmAkdhDFSz9snIBmu4pJuYbuNCG0qSqiQ0A6MNiqc85NDDbfUFGIP0wsUKl/R+hEiFppgnVoJ7agDzL38TrHGpLVY1VcL+olzDR84y1g8gC+Dumr7wIDAQAB
  facilityAdmin:
    roleName: facility-admin
    roleId: 9da3a031-0c76-4077-9176-facfe70b12bc
    clientId: f806ea15-8a99-48f9-9c5d-a4602ae7b9db
    groupId: 860560da-911e-4db1-92f2-0cbbaad8f7b3
  facilityStaff:
    roleName: facility-staff
    roleId: e5573b4d-2805-475b-8e59-d2c7c9de499e
    clientId: f806ea15-8a99-48f9-9c5d-a4602ae7b9db
    groupId: 84682840-4c21-428d-b2d5-06e6298be1cc
analytics:
  datasource: tcp://localhost:9000?debug=true
facility:
  upload:
    columns: "facilityCode,facilityName,contact,operatingHourStart,operatingHourEnd,category,type,status,addressLine1,addressLine2,district,state,pincode,geoLocationLat,geoLocationLon,adminName,adminMobile"
    required: "facilityCode,facilityName,contact,addressLine1,addressLine1,district,state,pincode,adminName,adminMobile"
preenrollment:
  upload:
<<<<<<< HEAD
    columns: "phone,nationalId,dob,gender,name,email,addressLine1,addressLine2,district,state,pincode"
    required: "phone,nationalId,dob,gender,name,addressLine1,district,state,pincode"
=======
    columns: "phone,enrollmentScopeId,nationalId,dob,gender,name,email,addressLine1,addressLine2,district,state,pincode"
    required: "phone,enrollmentScopeId,nationalId,dob,gender,name,addressLine1,district,state,pincode"
>>>>>>> d67f4a22968fc0d8f5e31a903c140990031f5bbe
vaccinator:
  upload:
    columns: "code,name,nationalIdentifier,mobileNumber,email,status,facilityIds"
    required: "code,name,email,nationalIdentifier,mobileNumber,status,facilityIds"
kafka:
  bootstrapServers: localhost:9092
  notifyTopic: notify
  certifiedTopic: certified
  enrollmenttopic: enrollment
flagr:
  url: https://divoc.togosafe.gouv.tg/config
enrollmentcreation:
  maxretrycount: 10
  lengthofsuffixedenrollmentcode: 3
